staging -> main for v3.0.0 release
adobe/aepsdk-edgemedia-android pull request #80
Opened 2024-04-02 23:42 UTC by emdobrin

## Description

Major version update for Adobe Streaming Media for Edge Network for Adobe Experience Platform Mobile SDKs on Android compatible with Mobile Core 3.0.0. The current release includes the following changes:
- Updated the minimum supported Android API level to 21.
- Removed deprecated registerExtension API. Use the MobileCore.registerExtensions() API for registering extensions and initializing the SDK instead.

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-04-02 23:55 UTC, kevinlind requested changes

2024-04-02 23:55 UTC, kevinlind commented on code/testapp-kotlin/build.gradle.kts
> +}
The Kotlin test app is still using the SNAPSHOT builds.

2024-04-03 00:01 UTC, cacheung commented on code/testapp-kotlin/build.gradle.kts
> +    implementation("com.adobe.marketing.mobile:core:3.0.0-SNAPSHOT")
we need to remove the SNAPSHOT here

2024-04-03 00:07 UTC, cacheung approved these changes

2024-04-03 00:24 UTC, merged